# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-23 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name="Nom de l'association")),
                ('description', models.TextField(default='', verbose_name="Description de l'association")),
                ('validation_state', models.CharField(choices=[('MD', 'Missing documents'), ('SM', 'Submittable'), ('PE', 'Pending'), ('AC', 'Accepted'), ('RF', 'Refused')], default='MD', max_length=2, verbose_name='État de la validation')),
                ('logo', models.ImageField(upload_to='associations/logo', verbose_name="Logo de l'association")),
                ('banner', models.ImageField(upload_to='associations/banner', verbose_name="Bannière de l'association")),
                ('subscription_cost', models.IntegerField(default=0, verbose_name='Coût de la cotisation')),
                ('room', models.CharField(max_length=5, null=True, verbose_name="Local de l'association")),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_1', models.FileField(upload_to='admin_doc/%Y/')),
                ('doc_2', models.FileField(upload_to='admin_doc/%Y/')),
                ('doc_3', models.FileField(upload_to='admin_doc/%Y/')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_link', models.CharField(choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('YT', 'YouTube'), ('WE', 'Site internet'), ('MA', 'Mail'), ('OT', 'Autre')], max_length=2)),
                ('url', models.URLField()),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association')),
            ],
        ),
    ]
