# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statuses', models.FileField(upload_to='admin_doc/%Y/', verbose_name="Status de l'association")),
                ('internal_regulations', models.FileField(upload_to='admin_doc/%Y/', verbose_name='Règlement intérieur')),
                ('banking_account_info', models.FileField(upload_to='admin_doc/%Y/', verbose_name='RIB')),
                ('insurance', models.FileField(upload_to='admin_doc/%Y/', verbose_name='Assurances')),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='association',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='year',
        ),
        migrations.AlterField(
            model_name='association',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='associations/banner', verbose_name="Bannière de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name="Description de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='associations/logo', verbose_name="Logo de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='room',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name="Local de l'association"),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
        migrations.AddField(
            model_name='document',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association'),
        ),
        migrations.AddField(
            model_name='document',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SchoolYear'),
        ),
    ]
