# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_auto_20160924_0255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField(blank=True, null=True, verbose_name='Commentaires sur le refus')),
                ('Date_of_comment', models.DateTimeField(auto_now=True, verbose_name='Date du commentaire')),
                ('Association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association')),
            ],
        ),
    ]
