# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('accounts', '0002_auto_20160510_1608'),
        ('associations', '0003_refusal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_subscription', models.DateField(auto_now_add=True)),
                ('is_board', models.BooleanField(default=False)),
                ('role', models.CharField(choices=[('PR', 'Président'), ('VP', 'Vice-Président'), ('TR', 'Trésorier'), ('RC', 'Responsable communications'), ('SC', 'Secrétaire'), ('OT', 'Autre')], max_length=2)),
                ('custom_role', models.CharField(blank=True, default='', max_length=30)),
                ('accepted', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='association',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name="Description de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='room',
            field=models.CharField(blank=True, default='', max_length=5, verbose_name="Local de l'association"),
        ),
        migrations.AlterField(
            model_name='refusal',
            name='Text',
            field=models.TextField(blank=True, default='', verbose_name='Commentaires sur le refus'),
        ),
        migrations.AddField(
            model_name='membership',
            name='association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associations.Association'),
        ),
        migrations.AddField(
            model_name='membership',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.SchoolYear'),
        ),
        migrations.AddField(
            model_name='association',
            name='members',
            field=models.ManyToManyField(through='associations.Membership', to='accounts.Account'),
        ),
    ]
