# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0004_auto_20160927_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refusal',
            old_name='Association',
            new_name='association',
        ),
        migrations.RenameField(
            model_name='refusal',
            old_name='Date_of_comment',
            new_name='comment_date',
        ),
        migrations.RenameField(
            model_name='refusal',
            old_name='Text',
            new_name='text',
        ),
    ]
