# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-26 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0005_auto_20170206_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='banner',
            field=models.ImageField(default='associations/banner/default.png', upload_to='associations/banner', verbose_name="Bannière de l'association"),
        ),
        migrations.AlterField(
            model_name='association',
            name='logo',
            field=models.ImageField(default='associations/logo/default.png', upload_to='associations/logo', verbose_name="Logo de l'association"),
        ),
    ]
