# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-02-08 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0006_auto_20180126_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='subscription_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Coût de la cotisation'),
        ),
    ]
